BEGIN;

CREATE TYPE "GooglePlaceAccessOverride" AS ENUM (
  'VERIFIED_PUBLIC',
  'VERIFIED_PRIVATE',
  'VERIFIED_NON_COURSE'
);

CREATE TABLE "GooglePlaceReview" (
  "id" TEXT NOT NULL,
  "googlePlaceId" TEXT NOT NULL,
  "accessOverride" "GooglePlaceAccessOverride",
  "name" TEXT NOT NULL,
  "classification" TEXT NOT NULL,
  "evidenceUrl" TEXT NOT NULL,
  "reviewedAt" TIMESTAMP(3) NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "canonicalPlaceId" TEXT,
  "canonicalName" TEXT,
  "canonicalAddress" TEXT,
  "canonicalWebsiteUrl" TEXT,
  "canonicalPhone" TEXT,
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "retainWhenCanonicalAbsent" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "GooglePlaceReview_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "GooglePlaceReview_googlePlaceId_key"
ON "GooglePlaceReview"("googlePlaceId");

CREATE INDEX "GooglePlaceReview_active_accessOverride_idx"
ON "GooglePlaceReview"("active", "accessOverride");

CREATE INDEX "GooglePlaceReview_canonicalPlaceId_idx"
ON "GooglePlaceReview"("canonicalPlaceId");

CREATE INDEX "AutomationRun_startedAt_idx"
ON "AutomationRun"("startedAt");

CREATE INDEX "AutomationRun_promptVersion_startedAt_idx"
ON "AutomationRun"("promptVersion", "startedAt");

CREATE INDEX "CourseProbe_observedAt_idx"
ON "CourseProbe"("observedAt");

CREATE INDEX "CourseAutomationDiscovery_createdAt_idx"
ON "CourseAutomationDiscovery"("createdAt");

CREATE INDEX "TeeTimeMatch_firstSeenAt_idx"
ON "TeeTimeMatch"("firstSeenAt");

-- Seed all exact-ID reviews that were previously held in runtime registries. Records that were
-- both identity overrides and duplicate aliases are intentionally represented by one merged row.
INSERT INTO "GooglePlaceReview" (
  "id",
  "googlePlaceId",
  "accessOverride",
  "name",
  "classification",
  "evidenceUrl",
  "reviewedAt",
  "active",
  "canonicalPlaceId",
  "canonicalName",
  "canonicalAddress",
  "canonicalWebsiteUrl",
  "canonicalPhone",
  "latitude",
  "longitude",
  "retainWhenCanonicalAbsent",
  "updatedAt"
)
VALUES
  (
    'google-place-review-01',
    'ChIJHRdhRQt16IkRnZxbawELtdM',
    'VERIFIED_PUBLIC',
    'Grassy Hill Country Club',
    'PUBLIC_GOLF_COURSE',
    'https://grassyhillcountryclub.com/',
    '2026-07-11 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    41.2675142,
    -73.044987,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-02',
    'ChIJUTDSFL-w5IkRtjT_2vg_TJM',
    'VERIFIED_PRIVATE',
    'Old Sandwich Golf Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.osgolfclub.com/public',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-03',
    'ChIJa0Z9c_5QwokR83AzfcoIODI',
    'VERIFIED_PRIVATE',
    'Liberty National Golf Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.libertynationalgc.com/public-golf',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-04',
    'ChIJ7cBXOMNRwokREKeDC0xNIrY',
    'VERIFIED_PRIVATE',
    'Bayonne Golf Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.bayonnegolfclub.com/Membership',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-05',
    'ChIJwYHDYQ5VwokRfkjeAFO-rcY',
    'VERIFIED_PRIVATE',
    'Forest Hill Field Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://foresthillfc.com/about',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-06',
    'ChIJmYaOBZeqw4kR8uLQ3-n-ies',
    'VERIFIED_PRIVATE',
    'Montclair Golf Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.montclairgolfclub.org/',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-07',
    'ChIJMXRRcFvo5YkRkNXOrqSfVGM',
    'VERIFIED_PRIVATE',
    'Shelter Harbor Golf Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.shgcri.com/',
    '2026-07-12 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-08',
    'ChIJy0obgpGr2YgR3puygnLMK5M',
    'VERIFIED_PRIVATE',
    'Shell Bay Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://shellbayclub.com/',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-09',
    'ChIJ0fUoNOn24YkRd7n-n1PQsls',
    'VERIFIED_PRIVATE',
    'Baker Hill Golf Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.bakerhill.org/guest-information/frequently-asked-questions',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-10',
    'ChIJ-5eDKiZ64YkROEiuRnTjEKw',
    'VERIFIED_PRIVATE',
    'Dublin Lake Club Golf Course',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://home.dublinlake.org/default.aspx?E=6&p=home',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-11',
    'ChIJXdJQJmTpwIcRsoa_jpffsqs',
    'VERIFIED_PRIVATE',
    '18th Hole - Hallbrook CC',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://www.hallbrookcc.org/guest-information',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-12',
    'ChIJtVWUTNtX0VQR4I_SquYKOr4',
    'VERIFIED_PRIVATE',
    'Baywood Golf & Country Club',
    'PRIVATE_MEMBER_CONTROLLED',
    'https://baywoodgcc.com/membership/',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-13',
    'ChIJaWYTRqBbwokRONcYEIxCk1k',
    'VERIFIED_NON_COURSE',
    'NEXUS Golf Club',
    'INDOOR_SIMULATOR',
    'https://www.nexusgolf.com/contact',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-14',
    'ChIJ7dQcqrv5wokRIats-Rg1dZo',
    'VERIFIED_NON_COURSE',
    'BackyardSwingsStudio',
    'NON_COURSE_BUSINESS',
    'https://www.google.com/maps/search/?api=1&query_place_id=ChIJ7dQcqrv5wokRIats-Rg1dZo&query=BackyardSwingsStudio',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-15',
    'ChIJdZB9I4hhwokRFfvXRLrWvi8',
    'VERIFIED_NON_COURSE',
    'Q5C9+8VQ New York',
    'NON_COURSE_BUSINESS',
    'https://www.google.com/maps/search/?api=1&query_place_id=ChIJdZB9I4hhwokRFfvXRLrWvi8&query=Q5C9%2B8VQ%20New%20York',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-16',
    'ChIJy4_CTDEtDogR9wxAr-a-VGI',
    'VERIFIED_NON_COURSE',
    'Chicago Golf Authority',
    'INDOOR_SIMULATOR',
    'https://chicagogolfauthority.com/pages/how-it-works',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-17',
    'ChIJ67JAVPK12YgRnl_JdjR_gFs',
    'VERIFIED_NON_COURSE',
    'Green Girls Golf',
    'SERVICE_OR_MEDIA',
    'https://www.greengirlsgolf.com/',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-18',
    'ChIJ6xdB1Jq02YgR4mExla8UqpE',
    'VERIFIED_NON_COURSE',
    'South Florida Golf Magazine',
    'SERVICE_OR_MEDIA',
    'https://nextdoor.com/pages/south-florida-golf-magazine-miami-beach-fl/',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-19',
    'ChIJQfF9gY612YgRgEZ2p_DUI0M',
    'VERIFIED_NON_COURSE',
    'Celebrity Amputee Golf Classic',
    'EVENT_ORGANIZATION',
    'https://projects.propublica.org/nonprofits/organizations/454693128',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-20',
    'ChIJ9zQbdAC72YgRyrZQ5alj1h4',
    'VERIFIED_NON_COURSE',
    'PGA TOUR Deliveries',
    'RETAIL_OR_DELIVERY',
    'https://www.google.com/maps/search/?api=1&query_place_id=ChIJ9zQbdAC72YgRyrZQ5alj1h4&query=PGA%20TOUR%20Deliveries',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-21',
    'ChIJbV3-V-av2YgRGc2i3GxAjEY',
    'VERIFIED_NON_COURSE',
    'Golf Miami 305',
    'INDOOR_SIMULATOR',
    'https://www.golfmiami305.com/',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-22',
    'ChIJw4LoQ3TL4YkR--PVXKkrk7I',
    'VERIFIED_NON_COURSE',
    'The Barn At Fox Run',
    'NON_COURSE_VENUE',
    'https://www.thebarnatfoxrunvt.com/',
    '2026-07-13 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-23',
    'ChIJu4ODUC01oFQRrHyJkM_URz4',
    'VERIFIED_NON_COURSE',
    'PARTEE GOLF AND GAMES, LLC',
    'INDOOR_SIMULATOR',
    'https://parteegolfgame.com/contact',
    '2026-07-14 00:00:00.000',
    true,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-24',
    'ChIJL7Z5avQFK4cRO4PIpaKi9iA',
    NULL,
    'Arizona Grand Golf Course',
    'COURSE_IDENTITY',
    'https://www.arizonagrandresort.com/golf/',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJL7Z5avQFK4cRO4PIpaKi9iA',
    'Arizona Grand Golf Course',
    '8000 S Arizona Grand Pkwy, Phoenix, AZ 85044, USA',
    'https://www.arizonagrandgolf.com/',
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-25',
    'ChIJAQAAgewFK4cRxjiU-zozIzs',
    NULL,
    'Arizona Grand Golf Course',
    'COURSE_IDENTITY_ALIAS',
    'https://www.arizonagrandresort.com/golf/',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJL7Z5avQFK4cRO4PIpaKi9iA',
    'Arizona Grand Golf Course',
    '8000 S Arizona Grand Pkwy, Phoenix, AZ 85044, USA',
    'https://www.arizonagrandgolf.com/',
    NULL,
    NULL,
    NULL,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-26',
    'ChIJ____iusFK4cReVCFj6EmIBQ',
    NULL,
    'Arizona Grand Golf Course',
    'COURSE_IDENTITY_ALIAS',
    'https://www.arizonagrandresort.com/golf/',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJL7Z5avQFK4cRO4PIpaKi9iA',
    'Arizona Grand Golf Course',
    '8000 S Arizona Grand Pkwy, Phoenix, AZ 85044, USA',
    'https://www.arizonagrandgolf.com/',
    NULL,
    NULL,
    NULL,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-27',
    'ChIJq6qqPcgFK4cRuYv0flb88dY',
    NULL,
    'Ahwatukee Golf Club',
    'COURSE_IDENTITY',
    'https://www.ahwatukeegolf.com/',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJq6qqPcgFK4cRuYv0flb88dY',
    'Ahwatukee Golf Club',
    '12432 S 48th St, Phoenix, AZ 85044, USA',
    'https://www.ahwatukeegolf.com/',
    '(480) 893-1161',
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-28',
    'ChIJ____G7MFK4cRf2hkJjIoEWo',
    NULL,
    'Ahwatukee Golf Club',
    'COURSE_IDENTITY_ALIAS',
    'https://www.ahwatukeegolf.com/',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJq6qqPcgFK4cRuYv0flb88dY',
    'Ahwatukee Golf Club',
    '12432 S 48th St, Phoenix, AZ 85044, USA',
    'https://www.ahwatukeegolf.com/',
    '(480) 893-1161',
    NULL,
    NULL,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-29',
    'ChIJq6qqv7QFK4cRZNsSs47toA8',
    NULL,
    'Ahwatukee Golf Club',
    'COURSE_IDENTITY_ALIAS',
    'https://www.ahwatukeegolf.com/',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJq6qqPcgFK4cRuYv0flb88dY',
    'Ahwatukee Golf Club',
    '12432 S 48th St, Phoenix, AZ 85044, USA',
    'https://www.ahwatukeegolf.com/',
    '(480) 893-1161',
    NULL,
    NULL,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'google-place-review-30',
    'ChIJj1vnKctZ4IkRr5BY1-F-5AE',
    NULL,
    'Stratton Golf Course',
    'DUPLICATE_ALIAS',
    'https://www.stratton.com/things-to-do/activities/stratton-golf/tour-the-course',
    '2026-07-13 00:00:00.000',
    true,
    'ChIJvbRuDR9Y4IkRe4pD0YaU5fQ',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP
  );

-- The original layout migration created this durable Course row. Reassert the evidence so
-- removal of the runtime fallback cannot regress Woodhaven's verified physical layout. Preserve
-- the original verification timestamp when it is already present.
UPDATE "Course"
SET
  "layoutHoleCounts" = ARRAY[9]::INTEGER[],
  "layoutHolesEvidenceUrl" = 'https://www.woodhavenctgolf.com/',
  "layoutHolesVerifiedAt" = COALESCE(
    "layoutHolesVerifiedAt",
    '2026-07-11 00:00:00.000'::TIMESTAMP(3)
  ),
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "googlePlaceId" = 'ChIJUypX_OHc54kRkpGKTvmSvSA'
AND (
  "layoutHoleCounts" IS DISTINCT FROM ARRAY[9]::INTEGER[]
  OR "layoutHolesEvidenceUrl" IS DISTINCT FROM 'https://www.woodhavenctgolf.com/'
  OR "layoutHolesVerifiedAt" IS NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM "Course"
    WHERE "googlePlaceId" = 'ChIJUypX_OHc54kRkpGKTvmSvSA'
    AND "layoutHoleCounts" = ARRAY[9]::INTEGER[]
    AND "layoutHolesEvidenceUrl" = 'https://www.woodhavenctgolf.com/'
    AND "layoutHolesVerifiedAt" IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'Expected a persisted Woodhaven Course with verified nine-hole layout evidence';
  END IF;
END $$;

COMMIT;
